import axios from 'axios';
import base64 from 'base-64';
import { Auth } from './auth';
import { ErrorHandler } from './errorHandler';
import crypto from 'crypto';

/**
 * StkPush class handles the STK Push request functionality for M-Pesa payments.
 * 
 * This class provides methods to:
 * - Generate secure passwords for API requests
 * - Send STK Push requests to initiate mobile payments
 * - Handle API responses and errors
 * 
 * The STK Push API allows merchants to initiate payment requests directly to 
 * customers' phones, prompting them to enter their M-Pesa PIN to authorize payments.
 */
export class StkPush {
    private auth: Auth; // Reference to the Auth class for token generation
    private baseUrl: string; // Base URL for the STK Push endpoint

    /**
     * Creates an instance of StkPush.
     * 
     * @param auth - An instance of the Auth class for token generation.
     *               This is used to obtain access tokens for API authentication.
     * @param sandbox - Whether to use the sandbox environment (default: true).
     *                 Set to false for production environment.
     * 
     * @example
     * ```typescript
     * const auth = new Auth('consumer-key', 'consumer-secret');
     * const stkPush = new StkPush(auth, true); // For sandbox environment
     * ```
     */
    constructor(auth: Auth, sandbox: boolean = true) {
        this.auth = auth;
        this.baseUrl = sandbox
            ? 'https://apisandbox.safaricom.et/mpesa/stkpush/v3/processrequest'
            : 'https://api.safaricom.et/mpesa/stkpush/v3/processrequest'
    }

    /**
     * Generates the password for the STK Push request.
     * 
     * The password is generated by:
     * 1. Concatenating the business shortcode, passkey and timestamp
     * 2. Hashing the concatenated string using SHA256
     * 3. Base64 encoding the hashed value
     * 
     * @param businessShortCode - The business shortcode (PayBill or Till Number).
     * @param passkey - The passkey provided by Safaricom during integration.
     * @param timestamp - The timestamp in the format YYYYMMDDHHmmss.
     * @returns The base64-encoded SHA256 hashed password.
     * 
     * @example
     * ```typescript
     * const timestamp = '20240101120000';
     * const password = stkPush.generatePassword('123456', 'mypasskey', timestamp);
     * ```
     */
    private generatePassword(businessShortCode: string, passkey: string, timestamp: string): string {
        const password = `${businessShortCode}${passkey}${timestamp}`;
        const hashedPassword = crypto
            .createHash('sha256')
            .update(password)
            .digest();
        return base64.encode(password.toString());
    }

    /**
     * Sends an STK Push request to initiate a payment via the Safaricom API.
     * 
     * This method:
     * 1. Generates necessary credentials (timestamp, password)
     * 2. Obtains an access token
     * 3. Prepares and validates the request payload
     * 4. Sends the request to M-Pesa API
     * 5. Handles the response
     * 
     * @param businessShortCode - The business shortcode (PayBill or Till Number).
     * @param passkey - The passkey provided by Safaricom during integration.
     * @param amount - The amount to be transacted (must be a positive number).
     * @param phoneNumber - The customer's phone number initiating the transaction.
     * @param callbackUrl - The HTTPS URL for receiving payment notifications.
     * @param accountReference - The account reference (max 12 characters).
     * @param transactionDesc - A description of the transaction (max 13 characters).
     * 
     * @returns Promise containing the API response data.
     *          Successful response includes CheckoutRequestID and ResponseDescription.
     * 
     * @throws MpesaError if the API request fails or returns an error.
     * @throws Error for network issues or invalid parameters.
     * 
     * @example
     * ```typescript
     * try {
     *   const result = await stkPush.sendStkPush(
     *     '174379',
     *     'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
     *     100,
     *     '254712345678',
     *     'https://example.com/callback',
     *     'INV001',
     *     'Payment for X'
     *   );
     *   console.log('Payment initiated:', result);
     * } catch (error) {
     *   console.error('Payment failed:', error);
     * }
     * ```
     */
    public async sendStkPush(
        businessShortCode: string,
        passkey: string,
        amount: number,
        phoneNumber: string,
        callbackUrl: string,
        accountReference: string,
        transactionDesc: string
    ): Promise<any> {
        try {
            // Generate the timestamp and password
            let timestamp = new Date()
                .toISOString()
                .replace(/[^0-9]/g, '')
                .slice(0, 14); // Format: YYYYMMDDHHmmss
            let password = this.generatePassword(businessShortCode, passkey, timestamp);

            // Generate the access token
            const { token: accessToken } = await this.auth.generateToken();

            businessShortCode = '1020';
            timestamp = '20240918055823';
            password = 'M2VkZGU2YWY1Y2RhMzIyOWRjMmFkMTRiMjdjOWIwOWUxZDFlZDZiNGQ0OGYyMDRiNjg0ZDZhNWM2NTQyNTk2ZA==';

            // Prepare the request payload
            const payload = {
                MerchantRequestID: Math.random().toString(36).substring(2, 15),
                BusinessShortCode: businessShortCode,
                Password: password,
                Timestamp: timestamp,
                TransactionType: "CustomerPayBillOnline",
                Amount: Math.round(amount), // Ensure amount is a whole number
                PartyA: phoneNumber.replace(/^0/, '251'), // Ensure phone number starts with 251
                PartyB: businessShortCode,
                PhoneNumber: phoneNumber.replace(/^0/, '251'), // Ensure phone number starts with 251
                CallBackURL: callbackUrl,
                AccountReference: accountReference.slice(0, 12), // Limit to 12 chars
                TransactionDesc: transactionDesc.slice(0, 13)  // Limit to 13 chars
            };

            // Send the STK Push request
            const response = await axios.post(this.baseUrl, payload, {
                headers: {
                    'Authorization': `Bearer ${accessToken}`
                },
            });

            // Check if the response is successful
            if (response.data?.ResponseCode === '0') {
                return response.data;
            } else {
                ErrorHandler.handleStkError(response.data);
            }
        } catch (error) {
            if (axios.isAxiosError(error)) {
                if (error.response) {
                    ErrorHandler.handleStkError(error.response.data);
                } else if (error.request) {
                    throw new Error('No response received from the API. Please check your network connection.');
                } else {
                    throw new Error(`Request setup error: ${error.message}`);
                }
            }

            const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
            throw new Error(`Failed to send STK Push request: ${errorMessage}`);
        }
    }
}